name: build
run-name: Build test

on:
  workflow_call:
    inputs:
      upload-build-artifacts:
        type: boolean
        required: false
        default: false
        description: Upload build artifacts

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}-build
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v3

      - name: Base Setup
        uses: jupyterlab/maintainer-tools/.github/actions/base-setup@v1

      - name: Build package
        run: |
          python -m pip install build wheel

          # Build jupytext package
          python -m build

          # Don't publish a tar.gz file over 1MB  (Issue #730)
          if (($(wc -c < dist/*.tar.gz) > 1000000)); then exit 1; fi

          # node_modules should not be in the package
          if (($(tar -tf dist/*.tar.gz | grep node_modules | wc -l)>0)); then echo "node_modules should not be included" && exit 1; fi

          # Check that the lab is there
          if (($(tar -tf dist/*.tar.gz | grep jupyterlab/packages/jupyterlab_jupytext/labextension/package.json$ | wc -l)==0)); then echo "Missing jupyterlab_jupytext" && exit 1; fi

          # Install package and extension
          python -m pip install dist/*.tar.gz

          echo "Install went OK"

      - name: Archive build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: dist
          path: dist
        if: ${{ inputs.upload-build-artifacts }}
