name: test-ui
run-name: Run UI tests with Galata

on:
  workflow_call:

env:
  WORKING_DIRECTORY: jupyterlab/packages/jupyterlab-jupytext-extension/ui-tests

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}-ui-test
  cancel-in-progress: true

jobs:
  test-pip:
    continue-on-error: false
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Base Setup
        uses: jupyterlab/maintainer-tools/.github/actions/base-setup@v1

      - name: Install from source (required for the pre-commit tests)
        run: python -m pip install -e '.[test-cov]'

      - name: Install galata
        working-directory: $WORKING_DIRECTORY
        env:
          PLAYWRIGHT_SKIP_BROWSER_DOWNLOAD: 1
        run: jlpm install

      - name: Install browser
        working-directory: $WORKING_DIRECTORY
        run: jlpm playwright install chromium

      - name: Integration tests
        working-directory: $WORKING_DIRECTORY
        run: jlpm playwright test
